/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/resort`; params?: Router.UnknownInputParams; } | { pathname: `/test-components`; params?: Router.UnknownInputParams; } | { pathname: `/test-greeting`; params?: Router.UnknownInputParams; } | { pathname: `/travel`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex01`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex012`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex02`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex03`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex04`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex05`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex06`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex07`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex08`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex09`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex10`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex11`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/resort`; params?: Router.UnknownOutputParams; } | { pathname: `/test-components`; params?: Router.UnknownOutputParams; } | { pathname: `/test-greeting`; params?: Router.UnknownOutputParams; } | { pathname: `/travel`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/Flexbox/ex01`; params?: Router.UnknownOutputParams; } | { pathname: `/Flexbox/ex012`; params?: Router.UnknownOutputParams; } | { pathname: `/Flexbox/ex02`; params?: Router.UnknownOutputParams; } | { pathname: `/Flexbox/ex03`; params?: Router.UnknownOutputParams; } | { pathname: `/Flexbox/ex04`; params?: Router.UnknownOutputParams; } | { pathname: `/Flexbox/ex05`; params?: Router.UnknownOutputParams; } | { pathname: `/Flexbox/ex06`; params?: Router.UnknownOutputParams; } | { pathname: `/Flexbox/ex07`; params?: Router.UnknownOutputParams; } | { pathname: `/Flexbox/ex08`; params?: Router.UnknownOutputParams; } | { pathname: `/Flexbox/ex09`; params?: Router.UnknownOutputParams; } | { pathname: `/Flexbox/ex10`; params?: Router.UnknownOutputParams; } | { pathname: `/Flexbox/ex11`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/resort${`?${string}` | `#${string}` | ''}` | `/test-components${`?${string}` | `#${string}` | ''}` | `/test-greeting${`?${string}` | `#${string}` | ''}` | `/travel${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/Flexbox/ex01${`?${string}` | `#${string}` | ''}` | `/Flexbox/ex012${`?${string}` | `#${string}` | ''}` | `/Flexbox/ex02${`?${string}` | `#${string}` | ''}` | `/Flexbox/ex03${`?${string}` | `#${string}` | ''}` | `/Flexbox/ex04${`?${string}` | `#${string}` | ''}` | `/Flexbox/ex05${`?${string}` | `#${string}` | ''}` | `/Flexbox/ex06${`?${string}` | `#${string}` | ''}` | `/Flexbox/ex07${`?${string}` | `#${string}` | ''}` | `/Flexbox/ex08${`?${string}` | `#${string}` | ''}` | `/Flexbox/ex09${`?${string}` | `#${string}` | ''}` | `/Flexbox/ex10${`?${string}` | `#${string}` | ''}` | `/Flexbox/ex11${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/resort`; params?: Router.UnknownInputParams; } | { pathname: `/test-components`; params?: Router.UnknownInputParams; } | { pathname: `/test-greeting`; params?: Router.UnknownInputParams; } | { pathname: `/travel`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex01`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex012`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex02`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex03`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex04`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex05`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex06`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex07`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex08`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex09`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex10`; params?: Router.UnknownInputParams; } | { pathname: `/Flexbox/ex11`; params?: Router.UnknownInputParams; };
    }
  }
}
